version: "3.9"

services:

    frutas-doce-mel-prod:
        image: tomcat:8.5
        container_name: frutas-doce-mel
        restart: always
        ports:
            - 3033:8080
        volumes:
            - ./frutas-doce-mel/tmpfiles:/usr/local/tomcat/tmpfiles
            - frutas-doce-mel-prod_bin:/usr/local/tomcat/bin
            - ./conf-tomcat/server.xml:/usr/local/tomcat/conf/server.xml
            - ./frutas-doce-mel/ExataAgro_ERP_WS.war:/usr/local/tomcat/webapps/ExataAgro_ERP_WS.war
        networks:
            - mysql-net

    mysql-5.7:
        image: mysql:5.7
        container_name: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: Ex@t@123,4
        ports:
            - 3306:3306
        volumes:
            - mysql-5.7:/var/lib/mysql
        networks:
            - mysql-net
                
volumes:
    frutas-doce-mel-prod_tmpfiles:
    frutas-doce-mel-prod_bin:
    mysql-5.7:

networks:
    mysql-net:

 